### ISSUE TITLE
feature request: reset tasks whose jobs are no longer running

### ISSUE THREAD

**Issue by kamdh** [stephen-fralich/parallel_sql#1]
When a job gets killed (e.g. for exceeding walltime) it doesn't always get the chance to change it's tasks' statuses from "picked up" to "available". It would therefore be nice for there to be an option to psu that resets those jobs to available. As far as I can see, this would require jobs to modify the database to record the jobid that picks up those tasks, so that it could be checked-for later.

I'd use this in a cron script to reset any tasks to available when their jobs are killed.

**Comment by stephen-fralich** [comment]
It already has this capability, psu --reset-sched.
