### ISSUE TITLE
--reset-sched depends on torque / qstat

### ISSUE THREAD

**Issue by groceryheist** [stephen-fralich/parallel_sql#3]
````
psu --reset-sched
qstat -x exited abnormally (RC = -1)
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Pg::db handle dbname=parallel;host=paralleldb at /sw/parallel_sql-20170322/bin/psu line 323.
````

This makes it difficult to use parallel-sql with checkpoint queue and the slurm scheduler. 

psu --reset-slurm works ok

**Comment by stephen-fralich** [comment]
Yes, --reset-sched is a historical artifact. Now the preferred options are --reset-pbs and --reset-slurm. The --reset-slurm option does the identical operation for Slurm that --reset-pbs (grandson of --reset-sched) does for Torque/PBS. The --reset-sched option was removed from the help (psu --help) in the version where I added Slurm support. I no longer work at the UW, so if the documentation needs updating on the local Wiki, you should contact help@uw.edu with Hyak as the first word in the subject.
